config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]

  match '/signup'   => "users#new"
  match '/signin'   => 'sessions#new'
  match '/signout'  => "sessions#destroy"

  root  :to         => "pages#home"
  match '/about'    => "pages#about"
  match '/contact'  => "pages#contact"
  match '/help'     => "pages#help"

end

app/models/user.rb
# == Schema Information
# Schema version: 20101106124457
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean(1)
#


class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not a valid email") unless
      #value =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
      value =~ /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  end
end

require 'digest'    # for password encryption via SHA2

class User < ActiveRecord::Base
  attr_accessor :password                   # virtual attribute - that means: no database column
  attr_accessible :name, :email, :password, :password_confirmation
  has_many :microposts, :dependent => :destroy
  default_scope :order => 'users.name ASC'

  validates :name,      :presence => true,
                        :length   => { :within => 3..30 }
  validates :email,     :presence   => true,
                        :email      => true,      # self written Validator in users_helper.rb
                        :uniqueness => { :case_sensitive => false }     # uniqueness => true , and ignoring the case
                        #:format    => { :with => email_regex }
  validates :password,  :presence     => true,
                        :length       => { :within => 6..64 },
                        :confirmation => true

  before_save :encrypt_password

  # CLASS Method defined through "self."authenticate
  def self.authenticate(email, submitted_password)
    user = User.find_by_email(email)
    (user && user.matching_password?(submitted_password)) ? user : nil
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = User.find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def self.per_page               # class method, used by will_paginate
    10
  end

  def feed
    microposts
    # Micropost.where("user_id =?", id)
  end

  def matching_password?(submitted_password)
    encrypt(submitted_password) == self.encrypted_password
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{self.salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:edit, :update, :show, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_rights, :only => [:destroy]

  def new
    if !signed_in?
      @user = User.new
      @title = 'Sign up'
    else
      redirect_to(root_path)
    end
  end

  def create
    if !signed_in?
      @user = User.new(params[:user])
      if @user.save
        flash[:success] = "Welcome, #{@user.name}!"
        sign_in @user
        redirect_to @user
      else
        @title = "Please try to Sign up again"
        @user.password = ''
        @user.password_confirmation = ''
        render :new
      end
    else
      redirect_to(root_path)
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @title = @user.name
  end

  def edit
    @title = "Edit your profile"
  end

  def update
      if @user.update_attributes(params[:user])
        flash[:success] = "Your profile was updated, #{@user.name}!"
        redirect_to @user
      else
        flash.now[:error] = "Your changes could not be saved!"
        @user.password = ''
        @user.password_confirmation = ''
        render :edit
      end
  end

  def index
    @users = User.paginate(:page => params[:page])
    @title = "All users"
  end

  def destroy    # only for admins
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end


  private

    def admin_rights
      redirect_to(root_path) unless current_user.admin?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user == @user # || current_user.admin?      # && signed_in? optional, wegen before_filer authenticate
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 } )
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/users/_user.html.haml
%li
  = gravatar_for user, :size => 40
  = link_to user.name, user
  - if signed_in? && current_user.admin? && !user.admin?
    = link_to ' | delete user', user, :method => :delete, :confirm => "This will delete the user. Continue?", :title => "Delete #{user.name}"

app/views/users/_user_form.html.haml
= form_for(@user) do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :password
    %br
    = f.password_field :password
  .field
    = f.label :password_confirmation, "Confirm Password"
    %br
    = f.password_field :password_confirmation
  .actions
    = f.submit @button_text

app/views/users/edit.html.haml
- @button_text = "Update"
= render :partial => "users/user_form"
%div
  = gravatar_for @user, :size => 60
  %a(href="http://gravatar.com/emails" target="_blank") change

app/views/users/index.html.haml
= will_paginate
%ul.users= render @users
= will_paginate

app/views/users/new.html.haml
- @button_text = "Sign up"
= render :partial => "users/user_form"

app/views/users/show.html.haml
%table.profile(summary="Profile information")
  %tr
    %td.main
      %h2
        = gravatar_for @user, :size => 60
        = @user.email
      - unless @user.microposts.empty?
        %table.microposts(summary="User microposts")
          = render @microposts
        = will_paginate @microposts

    %td.sidebar.round
      %strong Name
      = @user.name
      %br
      %strong URL
      = link_to user_url(@user), @user
      %br
      %strong Microposts
      = @user.microposts.count
      %br
      - if @user.admin?
        %strong --&gt; Admin &lt;--
      %br

      - if signed_in? && current_user == @user
        %strong= link_to 'Edit Profile', edit_user_path(current_user)