config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]

  match '/signup'   => "users#new"
  match '/signin'   => 'sessions#new'
  match '/signout'  => "sessions#destroy"

  root  :to         => "pages#home"
  match '/about'    => "pages#about"
  match '/contact'  => "pages#contact"
  match '/help'     => "pages#help"

end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to 'About', about_path
      %li= link_to 'Contact', contact_path
      %li= link_to 'Help', help_path
      %li
        %a(href="http://news.railstutorial.org/" target="_blank") News

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav.round
    %ul
      %li= link_to 'Home', root_path
      %li= link_to 'Users', users_path
      - if signed_in?
        %li= link_to 'Profile', current_user
        / %li= link_to 'Settings', edit_user_path(current_user)
        %li= link_to 'Sign out', signout_path, :method => :delete
      - else
        %li= link_to 'Sign in', signin_path

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  %script(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie'
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= title
    = csrf_meta_tag
    = render :partial => "layouts/stylesheets"
    = javascript_include_tag :defaults
  %body
    .container
      = render :partial => "layouts/header"
      %section.round
        - flash.each do |key, value|
          = content_tag(:div, value, :class => "flash #{key}")
        %h2= @title
        = yield
      = render :partial => "layouts/footer"
      = debug(params) if Rails.env.development?